"""Remove Person table and update other tables

Revision ID: 8cc7f7476344
Revises: 
Create Date: 2024-09-26 21:52:57.120587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc7f7476344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('parents_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('students_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('teachers_person_id_fkey', type_='foreignkey')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('teachers_person_id_fkey', 'persons', ['person_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('fullname')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('students_person_id_fkey', 'persons', ['person_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('fullname')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('parents_person_id_fkey', 'persons', ['person_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('fullname')

    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='persons_pkey'),
    sa.UniqueConstraint('email', name='persons_email_key')
    )
    # ### end Alembic commands ###
